### ISSUE TITLE
May you pls make a video on how to use this code. Thank you

### ISSUE THREAD

**Issue by EM0J1** [Norikiru/bloxflip-autocrash#10]
.

**Comment by carince** [comment]
Most likely not, but @nikosszzz has a plan to make a setup script to make setting it up easier.
For now, follow the instructions in the [README](https://github.com/Norikiru/bloxflip-autocrash#installation) file.

**Comment by carince** [comment]
Not really a problem for most people if you can follow instructions in README file, setup script will definitely still be added.
