### ISSUE TITLE
Tries in config is too high causing the bet to be 0.

### ISSUE THREAD

**Issue by Gonc90** [Norikiru/bloxflip-autocrash#14]
Why is this error happening is it because I have 0 robux on the account or something?

**Comment by Gonc90** [comment]
Yeah it looks like I needed a balance lol but how much is recommended to start with?

**Comment by carince** [comment]
> Yeah it looks like I needed a balance lol but how much is recommended to start with?

The recommended tries is 13 so if your going for the bare minimum of 0.01 bet then it would be 82 robux.
![image](https://user-images.githubusercontent.com/99774021/197308608-71618500-5c8a-4ace-abe1-e86366bc25b0.png)
