### ISSUE TITLE
Did token command and states its less than 1000.

### ISSUE THREAD

**Issue by CipherHYT** [Norikiru/bloxflip-autocrash#15]

**Comment by carince** [comment]
Noted. Will be removing the limit of 1000 later with a commit, will keep you updated.

**Comment by carince** [comment]
2459bde331cd0f7cabb2484061161fc2a55482a8 : Fixed by checking if token entry is empty instead of it being over 1000. 

Run the script again and update it with the updater.
If it does not update, run `git pull` in Powershell inside of the `bloxflip-autocrash` folder.
