### ISSUE TITLE
Why am I always losing

### ISSUE THREAD

**Issue by Gonc90** [Norikiru/bloxflip-autocrash#16]
Whatever I try to do I keep losing every single bet did I mess something up in the settings or something or does it work like this?

**Comment by carince** [comment]
> Whatever I try to do I keep losing every single bet did I mess something up in the settings or something or does it work like this?

You can try and see what's happening in the browser by setting headless to `false` and also verbose to `true` in the debugging section in the config.
When you run the script, a browser should pop up, do note to NOT do anything in the that browser cause it can affect it.

The debugging part of your config should look like this:
![image](https://user-images.githubusercontent.com/99774021/197309004-f0e10f66-67ab-452e-9ad6-6c23df1d7771.png)

Here's a list of things to check:
- Is the auto cashout at 2?
- Is it putting the correct bet in the input box?
- Is your internet is affecting it?

For now, do these steps above and also put down your OS and version.

**Comment by carince** [comment]
Closed due to inactivity, reopen when you still need assistance
