### ISSUE TITLE
says that i don't have git installed???

### ISSUE THREAD

**Issue by 11DD11** [Norikiru/bloxflip-autocrash#19]
it just says that it's not installed

i am new to this stuff sooo any help would be great  

the discord webhook also isn't working for me

**Comment by 11DD11** [comment]
bro someone help me ;-;

**Comment by nikosszzz** [comment]
@11DD11 Are you sure you have `git` installed on your computer?

Type `git` in a terminal/command prompt and send me what it tells you.

**Comment by carince** [comment]
Download [git](https://git-scm.com/downloads) and install it.
After that, redo your installation as guided by the [README](https://github.com/Norikiru/bloxflip-autocrash#installation) file.
