### ISSUE TITLE
[ELEMENTS]      Unable to query element: div.gameBlock.gameBet.crash_crashBet__D5Rs_ > button

### ISSUE THREAD

**Issue by gooffyahhhh** [Norikiru/bloxflip-autocrash#22]
tried to use  it  on a different pc and account same thing over and over again error  [ELEMENTS]  Unable to query element: div.gameBlock.gameBet.crash_crashBet__D5Rs_ > button

**Comment by gooffyahhhh** [comment]
anyone have this issue or have a fix for it

**Comment by azii7** [comment]
> tried to use it on a different pc and account same thing over and over again error [ELEMENTS] Unable to query element: div.gameBlock.gameBet.crash_crashBet__D5Rs_ > button

yeah same error is happening to me

**Comment by carince** [comment]
Bloxflip has most likely updated, might be pushing an update in a day or two.
Currently, I am on holiday and have no plans on fixing it till I am back.

**Comment by azii7** [comment]
> Bloxflip has most likely updated, might be pushing an update in a day or two.
> 
> Currently, I am on holiday and have no plans on fixing it till I am back.

Okay thanks.

**Comment by carince** [comment]
I have submitted a fix at the dev branch. To test the fix, go do the following:

- Open PowerShell inside of the bloxflip-autocrash folder. (Hold Shift then Right Click, there should be a option to launch PowerShell)
![image](https://user-images.githubusercontent.com/99774021/200792757-df6bc95a-d608-4066-8938-146afb87760f.png)
- Run the following commands:
`git checkout dev` then `git pull`

You **should** be able to use the patch without problems if you did the following correctly.
Please do note that you need to have **[git](https://git-scm.com/downloads)** installed and that you have cloned the repository using git or else this would not work.

Give feedback here if it doesn't work then well work it out.
Happy farming.

**Comment by carince** [comment]
Merged fix to main branch
