### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by EmmazMovies** [Norikiru/bloxflip-autocrash#25]
![Screenshot](https://user-images.githubusercontent.com/117547894/201497485-97cd98bb-942d-457d-a466-1c74ba13a279.png)

**Comment by carince** [comment]
Follow the [instructions](https://github.com/Norikiru/bloxflip-autocrash#installation) in the [README.md](https://github.com/Norikiru/bloxflip-autocrash#readme) file.
Most likely you have edited the example config and didn't rename it.

**Comment by EmmazMovies** [comment]
> Follow the [instructions](https://github.com/Norikiru/bloxflip-autocrash#installation) in the [README.md](https://github.com/Norikiru/bloxflip-autocrash#readme) file. Most likely you have edited the example config and didn't rename it.

I 100% Did Rename It

**Comment by EmmazMovies** [comment]
> Follow the [instructions](https://github.com/Norikiru/bloxflip-autocrash#installation) in the [README.md](https://github.com/Norikiru/bloxflip-autocrash#readme) file. Most likely you have edited the example config and didn't rename it.


https://user-images.githubusercontent.com/117547894/202848583-1164b67f-f8d8-42e3-a54c-4d3991d86dec.mp4

**Comment by carince** [comment]
Will be returning on this issue sometime, but currently I don't have the time to fix this.
I would probably need to do checks and add more info regarding what file its trying to look and what its subfolder is.
