### ISSUE TITLE
TimeoutError : Timeout exceeded while waiting for event

### ISSUE THREAD

**Issue by natesleeman1911** [Norikiru/bloxflip-autocrash#27]
![image](https://user-images.githubusercontent.com/119473866/204708876-737da941-fb84-4262-8c88-5f0458031d5c.png)

Any ideas how to fix this one?

**Comment by carince** [comment]
Its probably because its taking long for the Bloxflip to load, therefore it exceeded the timeout.
Make sure you have a stable connection and try again.
