### ISSUE TITLE
Autocrash sometimes does not cash out at 2x. 

### ISSUE THREAD

**Issue by SakaDiscord** [Norikiru/bloxflip-autocrash#31]
Autocrash sometimes does not cash out at 2x, causing loosing streaks.

**Comment by carince** [comment]
You can set the `headless` to `false` in the debugging section in your config file to be able to see the Chrome instance and see what its doing,

I need you to check for me the following:
- Does it set the autocrash to x2 on start?
- Is it because of internet problems/issues?

**Comment by SakaDiscord** [comment]
I checked. 

- It does set autocrash to 2x on start. (It sometimes doesnt.)
- I don't think but it could be because its just happening sometimes. 

I havent had the issue in a while now so i think its probably just a network issue from my side. 
Thanks for the help tho! I am looking forward to future updates.
