### ISSUE TITLE
When I do npm start run, I get an error

### ISSUE THREAD

**Issue by haydedanny** [Norikiru/bloxflip-autocrash#32]
I downloaded the files, extracted it, and then did cd C:\Users\[myUser]\Downloads\bloxflip-autocrash-main\bloxflip-autocrash-main>
After, I configured the config.json and ran it, but I got 
[UPDATER] Unable to fetch current hash, skipping. Is git installed?
Error: Command failed: git --git-dir "C:\Users\[myUser]\Downloads\bloxflip-autocrash-main\bloxflip-autocrash-main\.git" show -s --format=%h
fatal: not a git repository: 'C:\Users\[myUser]\Downloads\bloxflip-autocrash-main\bloxflip-autocrash-main\.git'
Am I missing anything?

**Comment by PerkZ999** [comment]
well is git installed?

**Comment by haydedanny** [comment]
yes

**Comment by haydedanny** [comment]
git version 2.38.1.windows.1
