### ISSUE TITLE
Fetching Failed

### ISSUE THREAD

**Issue by mlgdestroyer** [Norikiru/bloxflip-autocrash#34]
After running the bot it says:
> bloxflip-autocrash@1.1.2 start
> ts-node src/index.ts

[STARTUP]       Starting bloxflip-autocrash
[SUPPORT]       Support the developers by giving the repo a star! https://github.com/Norikiru/bloxflip-autocrash
[UPDATER]       Checking for updates...
[UPDATER]       No updates found.

But then it repeats '[PFETCH]        Fetching failed. trying again...', over and over again.

**Comment by krunkerhackman** [comment]
Same
