### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by carince** [Norikiru/bloxflip-autocrash#4]
Linux compatibility is still on works.

A few issues I have encountered trying to run the bot in a Ubuntu 20.04 LTS system:

- curl is being blocked by Cloudflare therefore we are not able to fetch information from API's
- Puppeteer documentation about using it on Linux are non-existent therefore the user needing to install the dependencies for puppeteer.
- more soon?

If you encounter more issues other than the mentioned issues above, reply with the issue down below, would love to get some feedback since this is supposed to be ran at VPS's which usually only run Linux.

**Comment by carince** [comment]
Hopefully fixed with this, go to dev branch to check it out. Needs some thorough testing.
[pfetch: migrate to browser fetch instead of curl](https://github.com/Norikiru/bloxflip-autocrash/commit/95342dce7ca3bac473c26c88025b16c3954de799)

**Comment by Tiebe** [comment]
Seems to work for me on arch
