### ISSUE TITLE
Please verify that the package.json has a valid "main" entry when running dev branch

### ISSUE THREAD

**Issue by michaelcortese** [Norikiru/bloxflip-autocrash#41]
`npm run start

> bloxflip-autocrash@2.1.1 start
> node build.mjs & node .

Deleting file: ./dist/pages/index.html
Deleting folder: ./dist/pages/public
Deleting folder: ./dist/pages
Deleting folder: ./dist
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: ENOENT: no such file or directory, scandir 'C:\Users\mjc40\3D Objects\bf\bloxflip-autocrash\src\backend\pages\public'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\mjc40\\3D Objects\\bf\\bloxflip-autocrash\\src\\backend\\pages\\public'
}

Node.js v18.16.0
node:internal/modules/cjs/loader:444
      throw err;
      ^

Error: Cannot find module 'C:\Users\mjc40\3D Objects\bf\bloxflip-autocrash\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:436:19)
    at Module._findPath (node:internal/modules/cjs/loader:678:18)
    at resolveMainPath (node:internal/modules/run_main:19:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:75:24)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\mjc40\\3D Objects\\bf\\bloxflip-autocrash\\package.json',   
  requestPath: 'C:\\Users\\mjc40\\3D Objects\\bf\\bloxflip-autocrash'
}

Node.js v18.16.0`

**Comment by carince** [comment]
Apparently I accidentally removed some of the needed packages for the new version to work. I pushed a new commit with some fixes and features.

## How to pull commit?
Within the `bloxflip-autocrash` folder, open a terminal and run the following commands:

- Pull new commit
```bash
git pull origin dev
```

- Install new dependencies
```bash
npm i
```

- Run the bot
```bash
npm run start
```

Feel free to reach out to me if the fix didn't work for you but if it did work you can go and close the issue. Thanks!

**Comment by michaelcortese** [comment]
still happening for me

**Comment by carince** [comment]
> still happening for me

~~Can you send a copy of the output by doing the commands above?~~

Found the reason why it's not working, apparently git doesnt push empty folders and the build doesn't take into account if the folder exists. Create a `public` folder at: `bloxflip-autocrash/src/backend/pages` and the error should go away.

**Comment by carince** [comment]
Inactive and fixed.
