### ISSUE TITLE
error when doing npm run  start

### ISSUE THREAD

**Issue by luxkatana** [Norikiru/bloxflip-autocrash#42]
luxkatana@DESKTOP-QEF01MR:~/autocrashblox$ npm run start

> bloxflip-autocrash@2.1.1 start
> rollup -c --configPlugin @rollup/plugin-typescript & node .

node:internal/modules/cjs/loader:446
      throw err;
      ^

Error: Cannot find module '/home/luxkatana/autocrashblox/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Module._findPath (node:internal/modules/cjs/loader:687:18)
    at resolveMainPath (node:internal/modules/run_main:15:25)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:24)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  path: '/home/luxkatana/autocrashblox/package.json',
  requestPath: '/home/luxkatana/autocrashblox'
}

Node.js v20.2.0
luxkatana@DESKTOP-QEF01MR:~/autocrashblox$ sh: 1: rollup: Permission denied

**Comment by Oogaboogaman21** [comment]
1. run cmd as administrator
2. type cd [the location of the autocrashblox folder]
3. now try npm i

**Comment by luxkatana** [comment]
Is there a reason why admin is required?

**Comment by Oogaboogaman21** [comment]
> Is there a reason why admin is required?

Running npm will need more permission because the bloxflip crash predictor needs to connect itself to the browser and blopflip and that requires administrator privilages.

If you do not trust this code then please do not run it

**Comment by luxkatana** [comment]
Are there any alternatives to this without admin? Would appreciate

**Comment by Oogaboogaman21** [comment]
> Are there any alternatives to this without admin? Would appreciate

Sorry for the late responce but no you cannot. But theres more problems other than running admin so I recommend not using this program until the issues are fixed. (You can test it on a virtual machine to see if it is a virus or not)

**Comment by luxkatana** [comment]
Alright, thanks for the respond

**Comment by carince** [comment]
AFAIK, you dont need to have admin perms for installing packages, I recommend using PowerShell instead of cmd since it is more up to date and less of a hassle to deal with.

Try doing the following steps and give me a update:
1. Open PowerShell in the bloxflip-autocrash folder
2. Run `npm i` to install dependencies/packages.
3. Run `npm run start` to start the bot.

**MAKE SURE YOU HAVE GONE THROUGH THE WHOLE INSTALLATION PROCESS.** (yes, also the configuration.)
Many people have opened many issues with them not going through the installation and configuration process 🤦‍♂️

**Comment by luxkatana** [comment]
Hey, this is the output of doing ``npm i`` btw(if it is useful to debug)
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> puppeteer@17.1.3 install C:\Users\BiBi\Downloads\martingale\node_modules\puppeteer
> node install.js

Downloading Chromium r1036745 - 187.2 Mb [====================] 100% 0.0s
Chromium (1036745) downloaded to C:\Users\BiBi\Downloads\martingale\node_modules\puppeteer\.local-chromium\win64-1036745
npm WARN bloxflip-autocrash@2.1.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 292 packages from 237 contributors and audited 293 packages in 32.048s

36 packages are looking for funding
  run `npm fund` for details

found 6 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```
when doing ``npm run start`` I get the following error
```
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Module.<anonymous> (C:\Users\BiBi\Downloads\martingale\node_modules\rollup\dist\bin\rollup:16:19)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\BiBi\\Downloads\\martingale\\node_modules\\rollup\\dist\\bin\\rollup'
  ]
}
internal/modules/cjs/loader.js:327
      throw err;
      ^

Error: Cannot find module 'C:\Users\BiBi\Downloads\martingale\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:319:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at resolveMainPath (internal/modules/run_main.js:12:25)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:68:24)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\BiBi\\Downloads\\martingale\\package.json',
  requestPath: 'C:\\Users\\BiBi\\Downloads\\martingale'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bloxflip-autocrash@2.1.1 start: `rollup -c --configPlugin @rollup/plugin-typescript & node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bloxflip-autocrash@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BiBi\AppData\Roaming\npm-cache\_logs\2023-07-23T13_21_18_089Z-debug.log
```

**Comment by carince** [comment]
> Hey, this is the output of doing `npm i` btw(if it is useful to debug)
> 
> ```
> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
> 
> > puppeteer@17.1.3 install C:\Users\BiBi\Downloads\martingale\node_modules\puppeteer
> > node install.js
> 
> Downloading Chromium r1036745 - 187.2 Mb [====================] 100% 0.0s
> Chromium (1036745) downloaded to C:\Users\BiBi\Downloads\martingale\node_modules\puppeteer\.local-chromium\win64-1036745
> npm WARN bloxflip-autocrash@2.1.1 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> added 292 packages from 237 contributors and audited 293 packages in 32.048s
> 
> 36 packages are looking for funding
>   run `npm fund` for details
> 
> found 6 moderate severity vulnerabilities
>   run `npm audit fix` to fix them, or `npm audit` for details
> ```
> 
> when doing `npm run start` I get the following error
> 
> ```
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
>     at Module.require (internal/modules/cjs/loader.js:1042:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Module.<anonymous> (C:\Users\BiBi\Downloads\martingale\node_modules\rollup\dist\bin\rollup:16:19)
>     at Module._compile (internal/modules/cjs/loader.js:1156:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\BiBi\\Downloads\\martingale\\node_modules\\rollup\\dist\\bin\\rollup'
>   ]
> }
> internal/modules/cjs/loader.js:327
>       throw err;
>       ^
> 
> Error: Cannot find module 'C:\Users\BiBi\Downloads\martingale\dist\index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:319:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
>     at resolveMainPath (internal/modules/run_main.js:12:25)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:68:24)
>     at internal/main/run_main_module.js:18:47 {
>   code: 'MODULE_NOT_FOUND',
>   path: 'C:\\Users\\BiBi\\Downloads\\martingale\\package.json',
>   requestPath: 'C:\\Users\\BiBi\\Downloads\\martingale'
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bloxflip-autocrash@2.1.1 start: `rollup -c --configPlugin @rollup/plugin-typescript & node .`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bloxflip-autocrash@2.1.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\BiBi\AppData\Roaming\npm-cache\_logs\2023-07-23T13_21_18_089Z-debug.log
> ```

I think it would be better if we tried using the dev channel and see if that would work since it has a full rewrite that I still haven't pushed to the main branch. Refer to #43 on how to change to the dev channel, you should be able to see my comment regarding that.

**Comment by luxkatana** [comment]
from the ``dev`` branch I get this when doing ``npm i``
```
> puppeteer@17.1.3 install C:\Users\BiBi\Downloads\bloxflip-autocrash\node_modules\puppeteer
> node install.js

Downloading Chromium r1036745 - 187.2 Mb [====================] 100% 0.0s
Chromium (1036745) downloaded to C:\Users\BiBi\Downloads\bloxflip-autocrash\node_modules\puppeteer\.local-chromium\win64-1036745

> @swc/core@1.3.59 postinstall C:\Users\BiBi\Downloads\bloxflip-autocrash\node_modules\@swc\core
> node postinstall.js

npm WARN bloxflip-autocrash@2.1.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-darwin-arm64@1.3.59 (node_modules\@swc\core-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-darwin-arm64@1.3.59: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-arm64-musl@1.3.59 (node_modules\@swc\core-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-arm64-musl@1.3.59: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-arm64-gnu@1.3.59 (node_modules\@swc\core-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-arm64-gnu@1.3.59: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-arm-gnueabihf@1.3.59 (node_modules\@swc\core-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-arm-gnueabihf@1.3.59: wanted {"osnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-x64-gnu@1.3.59 (node_modules\@swc\core-linux-x64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-x64-gnu@1.3.59: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-linux-x64-musl@1.3.59 (node_modules\@swc\core-linux-x64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-linux-x64-musl@1.3.59: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-win32-arm64-msvc@1.3.59 (node_modules\@swc\core-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-win32-arm64-msvc@1.3.59: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-darwin-x64@1.3.59 (node_modules\@swc\core-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-darwin-x64@1.3.59: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @swc/core-win32-ia32-msvc@1.3.59 (node_modules\@swc\core-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @swc/core-win32-ia32-msvc@1.3.59: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 296 packages from 247 contributors and audited 306 packages in 254.295s

56 packages are looking for funding
  run `npm fund` for details

found 4 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

Unfortunately I get this when running ``npm run start``
```
> bloxflip-autocrash@2.1.1 start C:\Users\BiBi\Downloads\bloxflip-autocrash
> node build.mjs --run

internal/modules/cjs/loader.js:998
    throw new ERR_REQUIRE_ESM(filename);
    ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\BiBi\Downloads\bloxflip-autocrash\build.mjs
    at Module.load (internal/modules/cjs/loader.js:998:11)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bloxflip-autocrash@2.1.1 start: `node build.mjs --run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bloxflip-autocrash@2.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BiBi\AppData\Roaming\npm-cache\_logs\2023-07-27T20_11_42_148Z-debug.log
```

it is no problem if I can't run this repository, I was just browsing through github for some repository's related to bloxflip.

Thanks for responding do this issue.
