### ISSUE TITLE
▲ CLIENT > CRASH  Failed to join game

### ISSUE THREAD

**Issue by 0buttercup** [Norikiru/bloxflip-autocrash#44]
does this on every attempt to join game

**Comment by Sightem** [comment]
seconding this

**Comment by carince** [comment]
Ill try to fix it later, been busy the past week so bare with me till I get this fixed.

**Comment by carince** [comment]
@0buttercup @Sightem 

Completely forgot to fix the issue (whoops mb), apparently Bloxflip just changed its API url for fetching user info. Pushed the changes to the dev branch, for how to use the dev branch refer to: https://github.com/carince/bloxflip-autocrash/issues/43#issuecomment-1646724977

I might also push this to the main branch since I feel like the dev branch has been stale and probably doesn't need more updates, but it definitely needs more testing. Ill update you guys on that when I get to merge it to the main branch. Cheers.

**Comment by Sightem** [comment]
> @0buttercup @Sightem
> 
> Completely forgot to fix the issue (whoops mb), apparently Bloxflip just changed its API url for fetching user info. Pushed the changes to the dev branch, for how to use the dev branch refer to: [#43 (comment)](https://github.com/carince/bloxflip-autocrash/issues/43#issuecomment-1646724977)
> 
> I might also push this to the main branch since I feel like the dev branch has been stale and probably doesn't need more updates, but it definitely needs more testing. Ill update you guys on that when I get to merge it to the main branch. Cheers.

I'm trying it out currently, and it still has the same problem by the looks of it

```json
{
    "auth": "auth",
    "bet": {
        "tries": 12,
        "startingBet": 0,
        "autoCashout": 2
    },
    "rain": {
        "enabled": true,
        "minimum": 0,
        "notifications": {
            "os_notifs": false,
            "webhook": {
                "enabled": false,
                "link": "",
                "ping_id": 0
            }
        }
    },
    "updater": {
        "enabled": false,
        "autoUpdate": false
    },
    // For debugging purposes only, dont touch if you dont know what you are doing
    "debugging": {
        "headless": false,
        "verbose": true
    }
}
```
```
bloxflip-autocrash@2.1.1 start
node build.mjs --run

Deleting file: ./dist/index.js
Deleting file: ./dist/pages/index.html
Deleting file: ./dist/pages/public/index.js
Deleting file: ./dist/pages/public/socket.io.js
Deleting folder: ./dist/pages/public
Deleting folder: ./dist/pages
Deleting file: ./dist/userscript.js
Deleting folder: ./dist
Building Backend...
Successfully built Backend!
Building UserScript...
Successfully built UserScript!
Building Analytics...
Successfully built Analytics!
Running bloxflip-autocrash...
 STARTUP  Starting bloxflip-autocrash
 SUPPORT  Support the developers by giving the repo a star! https://github.com/Norikiru/bloxflip-autocrash
 CONFIG  Successfully fetched config.
 SERVER  Successfully started server, listening on port 6580.
 BROWSER  Successfully started browser
 BLOXFLIP  Successfully set up page for Bloxflip
 LOGS  Successfully created log file: "C:\Users\Sightem\Documents\bloxflip-autocrash\logs\8-17-2023_10-27-0.txt"
 USER  Fetching user information.
 USER  Successfully logged in!
Username: usernamehere
ID: idhere
Balance: robuxhere R$
 SERVER  SzuTK93xdbJESIO_AAAB has connected.
 CLIENT > SERVER  Successfully connected to server with ID: SzuTK93xdbJESIO_AAAB
 CLIENT > CONFIG  Successfully fetched config.
 CLIENT > BF  Successfully connected to Bloxflip WebSocket
 CLIENT > BF  Successfully authorized account.
 ▲ CLIENT > CRASH  Failed to join game
 ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 3.58x
 ▲ CLIENT > CRASH  Failed to join game
 ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 1.25x
 ▲ CLIENT > CRASH  Failed to join game
 ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 9.28x
```

**Comment by carince** [comment]
> > @0buttercup @Sightem
> > Completely forgot to fix the issue (whoops mb), apparently Bloxflip just changed its API url for fetching user info. Pushed the changes to the dev branch, for how to use the dev branch refer to: [#43 (comment)](https://github.com/carince/bloxflip-autocrash/issues/43#issuecomment-1646724977)
> > I might also push this to the main branch since I feel like the dev branch has been stale and probably doesn't need more updates, but it definitely needs more testing. Ill update you guys on that when I get to merge it to the main branch. Cheers.
> 
> I'm trying it out currently, and it still has the same problem by the looks of it
> 
> ```json
> {
>     "auth": "auth",
>     "bet": {
>         "tries": 12,
>         "startingBet": 0,
>         "autoCashout": 2
>     },
>     "rain": {
>         "enabled": true,
>         "minimum": 0,
>         "notifications": {
>             "os_notifs": false,
>             "webhook": {
>                 "enabled": false,
>                 "link": "",
>                 "ping_id": 0
>             }
>         }
>     },
>     "updater": {
>         "enabled": false,
>         "autoUpdate": false
>     },
>     // For debugging purposes only, dont touch if you dont know what you are doing
>     "debugging": {
>         "headless": false,
>         "verbose": true
>     }
> }
> ```
> 
> ```
> bloxflip-autocrash@2.1.1 start
> node build.mjs --run
> 
> Deleting file: ./dist/index.js
> Deleting file: ./dist/pages/index.html
> Deleting file: ./dist/pages/public/index.js
> Deleting file: ./dist/pages/public/socket.io.js
> Deleting folder: ./dist/pages/public
> Deleting folder: ./dist/pages
> Deleting file: ./dist/userscript.js
> Deleting folder: ./dist
> Building Backend...
> Successfully built Backend!
> Building UserScript...
> Successfully built UserScript!
> Building Analytics...
> Successfully built Analytics!
> Running bloxflip-autocrash...
>  STARTUP  Starting bloxflip-autocrash
>  SUPPORT  Support the developers by giving the repo a star! https://github.com/Norikiru/bloxflip-autocrash
>  CONFIG  Successfully fetched config.
>  SERVER  Successfully started server, listening on port 6580.
>  BROWSER  Successfully started browser
>  BLOXFLIP  Successfully set up page for Bloxflip
>  LOGS  Successfully created log file: "C:\Users\Sightem\Documents\bloxflip-autocrash\logs\8-17-2023_10-27-0.txt"
>  USER  Fetching user information.
>  USER  Successfully logged in!
> Username: usernamehere
> ID: idhere
> Balance: robuxhere R$
>  SERVER  SzuTK93xdbJESIO_AAAB has connected.
>  CLIENT > SERVER  Successfully connected to server with ID: SzuTK93xdbJESIO_AAAB
>  CLIENT > CONFIG  Successfully fetched config.
>  CLIENT > BF  Successfully connected to Bloxflip WebSocket
>  CLIENT > BF  Successfully authorized account.
>  ▲ CLIENT > CRASH  Failed to join game
>  ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 3.58x
>  ▲ CLIENT > CRASH  Failed to join game
>  ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 1.25x
>  ▲ CLIENT > CRASH  Failed to join game
>  ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 9.28x
> ```

Since your config says that Chrome is not headless, can you open the Developer Tools (F12) and check the console? It should show an error, a screenshot would do.

**Comment by Sightem** [comment]
> > > @0buttercup @Sightem
> > > Completely forgot to fix the issue (whoops mb), apparently Bloxflip just changed its API url for fetching user info. Pushed the changes to the dev branch, for how to use the dev branch refer to: [#43 (comment)](https://github.com/carince/bloxflip-autocrash/issues/43#issuecomment-1646724977)
> > > I might also push this to the main branch since I feel like the dev branch has been stale and probably doesn't need more updates, but it definitely needs more testing. Ill update you guys on that when I get to merge it to the main branch. Cheers.
> > 
> > 
> > I'm trying it out currently, and it still has the same problem by the looks of it
> > ```json
> > {
> >     "auth": "auth",
> >     "bet": {
> >         "tries": 12,
> >         "startingBet": 0,
> >         "autoCashout": 2
> >     },
> >     "rain": {
> >         "enabled": true,
> >         "minimum": 0,
> >         "notifications": {
> >             "os_notifs": false,
> >             "webhook": {
> >                 "enabled": false,
> >                 "link": "",
> >                 "ping_id": 0
> >             }
> >         }
> >     },
> >     "updater": {
> >         "enabled": false,
> >         "autoUpdate": false
> >     },
> >     // For debugging purposes only, dont touch if you dont know what you are doing
> >     "debugging": {
> >         "headless": false,
> >         "verbose": true
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > bloxflip-autocrash@2.1.1 start
> > node build.mjs --run
> > 
> > Deleting file: ./dist/index.js
> > Deleting file: ./dist/pages/index.html
> > Deleting file: ./dist/pages/public/index.js
> > Deleting file: ./dist/pages/public/socket.io.js
> > Deleting folder: ./dist/pages/public
> > Deleting folder: ./dist/pages
> > Deleting file: ./dist/userscript.js
> > Deleting folder: ./dist
> > Building Backend...
> > Successfully built Backend!
> > Building UserScript...
> > Successfully built UserScript!
> > Building Analytics...
> > Successfully built Analytics!
> > Running bloxflip-autocrash...
> >  STARTUP  Starting bloxflip-autocrash
> >  SUPPORT  Support the developers by giving the repo a star! https://github.com/Norikiru/bloxflip-autocrash
> >  CONFIG  Successfully fetched config.
> >  SERVER  Successfully started server, listening on port 6580.
> >  BROWSER  Successfully started browser
> >  BLOXFLIP  Successfully set up page for Bloxflip
> >  LOGS  Successfully created log file: "C:\Users\Sightem\Documents\bloxflip-autocrash\logs\8-17-2023_10-27-0.txt"
> >  USER  Fetching user information.
> >  USER  Successfully logged in!
> > Username: usernamehere
> > ID: idhere
> > Balance: robuxhere R$
> >  SERVER  SzuTK93xdbJESIO_AAAB has connected.
> >  CLIENT > SERVER  Successfully connected to server with ID: SzuTK93xdbJESIO_AAAB
> >  CLIENT > CONFIG  Successfully fetched config.
> >  CLIENT > BF  Successfully connected to Bloxflip WebSocket
> >  CLIENT > BF  Successfully authorized account.
> >  ▲ CLIENT > CRASH  Failed to join game
> >  ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 3.58x
> >  ▲ CLIENT > CRASH  Failed to join game
> >  ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 1.25x
> >  ▲ CLIENT > CRASH  Failed to join game
> >  ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 9.28x
> > ```
> 
> Since your config says that Chrome is not headless, can you open the Developer Tools (F12) and check the console? It should show an error, a screenshot would do.

Sure, for the record only `http://localhost:6580/` is opened by the script, or at least thats the behavior on my machine
![image](https://github.com/carince/bloxflip-autocrash/assets/67830794/2bb3a00e-9968-459f-9eef-fd8ca721adb4)

**Comment by carince** [comment]
@Sightem Yes, it does go to that URL everytime so don't worry about that. Maybe try getting your auth token AGAIN from the Bloxflip website, sometimes the token is not the same when connecting to the WebSocket vs the website.

**Comment by kjrmz** [comment]
how to fix this problem?

**Comment by llllxzllll** [comment]
C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'rain')
    at pptr://__puppeteer_evaluation_script__:1:123
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async U (file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:5:613)
    at async file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:28:336

Node.js v20.9.0

>

**Comment by llllxzllll** [comment]
C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'rain')
    at pptr://__puppeteer_evaluation_script__:1:123
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async U (file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:5:613)
    at async file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:28:336

Node.js v20.9.0

**Comment by llllxzllll** [comment]
/C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'rain')
    at pptr://__puppeteer_evaluation_script__:1:123
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async U (file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:5:613)
    at async file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:28:336

Node.js v20.9.0

**Comment by llllxzllll** [comment]
`C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'rain')
    at pptr://__puppeteer_evaluation_script__:1:123
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async U (file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:5:613)
    at async file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:28:336

Node.js v20.9.0
`

**Comment by llllxzllll** [comment]
help me?!

**Comment by carince** [comment]
Stale
