### ISSUE TITLE
Fetching user data failed

### ISSUE THREAD

**Issue by KalchoBG** [Norikiru/bloxflip-autocrash#46]
im not sure if im doing something wrong because thats the first time im using this tool but id love if someone assisted me on this error:

 STARTUP  Starting bloxflip-autocrash
 SUPPORT  Support the developers by giving the repo a star! https://github.com/Norikiru/bloxflip-autocrash
 PFETCH  Fetching user data failed.
Error: undefined

**Comment by UnknownProflle** [comment]
same problem, help

**Comment by carince** [comment]
Stale
