### ISSUE TITLE
Never Joins the game

### ISSUE THREAD

**Issue by Azeh0** [Norikiru/bloxflip-autocrash#50]
I started it and it joined the very first game, lost, then never joined again i have left it on for about 30min. I put a 5R bet with a try rate at 2 and cash out at 2
 ▲ CLIENT > CRASH  Ignoring as we haven't joined this round: 1.61x
 ▲ CLIENT > CRASH  Failed to join game, bet was not placed before game started.

**Comment by CorruptedL1ght** [comment]
same here

**Comment by carince** [comment]
> I started it and it joined the very first game, lost, then never joined again i have left it on for about 30min. I put a 5R bet with a try rate at 2 and cash out at 2 ▲ CLIENT > CRASH Ignoring as we haven't joined this round: 1.61x ▲ CLIENT > CRASH Failed to join game, bet was not placed before game started.

Is the 5R$ set as the `startingBet` in the config? Works fine on with my testing.

**Comment by carince** [comment]
Stale issue
