### ISSUE TITLE
Can't create OS notification

### ISSUE THREAD

**Issue by 1-Mythical** [Norikiru/bloxflip-autocrash#52]
`Notifications are disabled
Reason: DisabledForUser Please make sure the app id is set correctly.`

**Comment by carince** [comment]
Notifications are most likely disabled on your OS.
![image](https://github.com/carince/bloxflip-autocrash/assets/99774021/8c2718fc-9f0c-446c-8f50-e1d7dcf03b0a)

Reference:
https://github.com/mikaelbr/node-notifier/issues/334

**Comment by carince** [comment]
Stale, closing.
