### ISSUE TITLE
Websocket closed unexpectedly

### ISSUE THREAD

**Issue by starbuckson9** [Norikiru/bloxflip-autocrash#55]
![Screenshot_2](https://github.com/carince/bloxflip-autocrash/assets/56242171/f379ef66-685d-40f2-9238-c9e51059caf8)

Sometimes the websocket will close unexpectedly and just never return, i've encountered on my 12th try and lost half of my robux.
How to fix or prevent?

**Comment by carince** [comment]
Still need to replicate it on my end, haven't had that issue.

**Comment by carince** [comment]
Stale
