### ISSUE TITLE
roulette?

### ISSUE THREAD

**Issue by wammmwmm** [Norikiru/bloxflip-autocrash#60]

**Comment by Crysiox** [comment]
i need this too

**Comment by wamuelo** [comment]
nvm did it myself just analytics not working otherwise fine

**Comment by Crysiox** [comment]
> nvm did it myself just analytics not working otherwise fine

could you post it on your profile. thanks!

**Comment by wamuelo** [comment]
yeah just gotta clean some shit cuz its horriably remade

**Comment by Crysiox** [comment]
> yeah just gotta clean some shit cuz its horriably remade

yay

**Comment by MidClient** [comment]
when

**Comment by Crysiox** [comment]
> yeah just gotta clean some shit cuz its horriably remade

Done yet?

**Comment by carince** [comment]
Im currently working on a implementation for roulette.
For now it can place bets and seems to be working well, but I would need to update analytics stuff to play well with roulette and crash game data.

**Comment by carince** [comment]
Released in [v3](https://github.com/carince/bloxflip-autogambler/releases/tag/v3), that has been pushed to the main branch.
