### ISSUE TITLE
 Fetching user data failed

### ISSUE THREAD

**Issue by starbuckson9** [Norikiru/bloxflip-autocrash#73]
![Screenshot_2](https://github.com/carince/bloxflip-autogambler/assets/56242171/f04fc7d3-2ab1-4986-9905-d789fe8e99f9)

Keep getting this error, it works fine at first but this error occur once i got disconnected

**Comment by starbuckson9** [comment]
it works like after 10-15 tries, but still get same error when npm start

**Comment by carince** [comment]
> it works like after 10-15 tries, but still get same error when npm start

What version are you using? Please send the output of the command: `git rev-parse --short HEAD` so I can check what commit you are on.

**Comment by starbuckson9** [comment]
> > it works like after 10-15 tries, but still get same error when npm start
> 
> What version are you using? Please send the output of the command: `git rev-parse --short HEAD` so I can check what commit you are on.

79445fe

**Comment by starbuckson9** [comment]
![Screenshot_3 (2)](https://github.com/carince/bloxflip-autogambler/assets/56242171/c1cbc355-5f77-4def-b7bc-26f1ff6c9706)
Fixed by adding this line into it

Credit: https://github.com/axios/axios/issues/4372

**Comment by carince** [comment]
Would you want to create a PR to get credits or would you want me to do it?

**Comment by starbuckson9** [comment]
> Would you want to create a PR to get credits or would you want me to do it?

Pls help me do it, im not familiar with github thingy

**Comment by carince** [comment]
> > Would you want to create a PR to get credits or would you want me to do it?
> 
> Pls help me do it, im not familiar with github thingy

You could use this video, its old but it should still work.
https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by hibdusne** [comment]
i have the same error

**Comment by hibdusne** [comment]
i added that and it still doesnt work
